source 'http://rubygems.org'
ruby '3.3.6'

gem 'activerecord'
gem 'activerecord-import'
gem 'trilogy'
# The published v1.3.0 has a bug for use with trilogy
gem 'active_record_union', git: 'https://github.com/brianhempel/active_record_union'
gem 'actionview'
gem 'activesupport'
gem 'addressable'
gem 'biodiversity'
gem 'capitalize-names'
gem 'charlock_holmes'
gem 'chronic'
gem 'colorize'
gem 'config'
gem 'counter_culture'
gem 'csv'
gem 'down'
gem 'dwc_agent'
gem 'dwc-archive'
gem 'elasticsearch', '~>7.17'
gem 'faraday-multipart'
gem 'faraday-typhoeus'
gem 'haml', '~>5.2.2'
gem 'htmlentities'
gem 'i18n'
gem 'i18n_data'
gem 'iso_country_codes'
gem 'mini_magick'
gem 'namae'
gem 'nokogiri'
gem 'oauth2'
gem 'oj'
gem 'omniauth-orcid'
gem 'pagy'
gem 'parallel'
gem 'pluck_to_hash'
gem 'pony'
gem 'puma'
gem 'rack-contrib'
gem 'rack-test'
gem 'rack-tracker'
gem 'redis'
gem 'require_all'
gem 'rest-client'
gem 'rss'
gem 'ruby-filemagic'
gem 'ruby-progressbar'
gem 'rubyzip'
gem 'sanitize'
gem 'sidekiq', '~>7'
gem 'sinatra'
gem 'sinatra-cacher'
gem 'sinatra-contrib'
gem 'sinatra-flash'
gem 'sinatra-outputbuffer'
gem 'sinatra-support'
gem 'sitemap_generator'
gem 'sort_alphabetical'
gem 'sparql-client'
gem 'typhoeus'
gem 'wikidata-client', git: 'https://github.com/dshorthouse/wikidata-client', branch: 'patch-1'

group :production do
  gem 'passenger'
end

group :test, :development do
  gem 'byebug'
  gem 'rake'
  gem 'rspec'
end
