source 'http://rubygems.org'
ruby '3.2.1'

gem 'activerecord'
gem 'activerecord-import'
gem 'active_record_union'
gem 'actionview'
gem 'activesupport'
gem 'addressable'
gem 'biodiversity'
gem 'capitalize-names'
gem 'charlock_holmes'
gem 'chronic'
gem 'colorize'
gem 'composite_primary_keys'
gem 'config'
gem 'counter_culture'
gem 'dwc_agent'
gem 'dwc-archive'
gem 'elasticsearch', '~>7.17'
gem 'haml', '~>5.2.2'
gem 'htmlentities'
gem 'i18n'
gem 'i18n_data'
gem 'iso_country_codes'
gem 'mysql2'
gem 'namae'
gem 'nokogiri'
gem 'oauth2'
gem 'omniauth-orcid'
gem 'oj'
gem 'pagy'
gem 'parallel'
gem 'pluck_to_hash'
gem 'pony'
gem 'rack-contrib'
gem 'rack-tracker'
gem 'rack-test'
gem 'redis'
gem 'require_all'
gem 'rest-client'
gem 'rgl'
gem 'rss'
gem 'ruby-filemagic'
gem 'ruby-progressbar'
gem 'rubysl-securerandom'
gem 'rubyzip'
gem 'sanitize'
gem 'sidekiq'
gem 'sinatra'
gem 'sinatra-cacher'
gem 'sinatra-contrib'
gem 'sinatra-outputbuffer'
gem 'sinatra-flash'
gem 'sinatra-support'
gem 'sitemap_generator'
gem 'sparql-client'
gem 'sucker_punch'
gem 'thin'
gem 'twitter'
gem 'typhoeus'
gem 'wikidata-client', git: 'https://github.com/dshorthouse/wikidata-client.git', branch: 'bump-dependencies'

group :production do
  gem 'passenger'
end

group :test, :development do
  gem 'byebug'
  gem 'rake'
  gem 'rspec'
end
