name: Bionomia

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      RUBY_VERSION: 2.7.1
      BUNDLER_VERSION: 2.2.0
      RACK_ENV: test
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
      MYSQL_HOST: localhost
      MYSQL_DATABASE: bionomia_test
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@473e4d8fe5dd94ee328fdfca9f8c9c7afc9dae5e
      with:
        ruby-version: ${{ env.RUBY_VERSION }}
        bundler-cache: true
    - name: Set up MySQL
      run: |
        sudo /etc/init.d/mysql start
    - name: Setup Database Config
      run: |
          cp config/settings/test.yml.sample config/settings/test.yml
          sed -i 's/MYSQL_HOST/${{ env.MYSQL_HOST }}/g' config/settings/test.yml
          sed -i 's/MYSQL_USERNAME/${{ env.MYSQL_USERNAME }}/g' config/settings/test.yml
          sed -i 's/MYSQL_PASSWORD/${{ env.MYSQL_PASSWORD }}/g' config/settings/test.yml
          sed -i 's/MYSQL_DATABASE/${{ env.MYSQL_DATABASE }}/g' config/settings/test.yml
    - name: Create database and import data
      run: |
          RACK_ENV=test bundle exec rake db:create:all
          RACK_ENV=test bundle exec rake db:schema:load
    - name: Configure sysctl limits
      run: |
          sudo swapoff -a
          sudo sysctl -w vm.swappiness=1
          sudo sysctl -w fs.file-max=262144
          sudo sysctl -w vm.max_map_count=262144
    - name: Runs Elasticsearch
      uses: elastic/elastic-github-actions/elasticsearch@master
      with:
        stack-version: 7.15.2
    - name: Create Elasticsearch synonyms.txt
      uses: 1arp/create-a-file-action@0.2
      with:
        path: '/usr/share/elasticsearch/config'
        file: 'synonyms.txt'
        content: |
          aaron => erin, ron, ronnie
    - name: Creates Elasticsearch indices
      run: |
          [ -f /usr/share/elasticsearch/config/synonyms.txt ] && echo "Synonyms file exists." || echo "Synonyms file does not exist."
          RACK_ENV=test bundle exec rake elastic:create:all
    - name: Run tests
      run: RACK_ENV=test bundle exec rake
