name: Bionomia

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      RUBY_VERSION: 2.7.1
      BUNDLER_VERSION: 2.2.0
      RACK_ENV: test
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
      MYSQL_HOST: localhost
      MYSQL_DATABASE: bionomia_test
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@473e4d8fe5dd94ee328fdfca9f8c9c7afc9dae5e
      with:
        ruby-version: ${{ env.RUBY_VERSION }}
        bundler-cache: true
    - name: Set up MySQL
      run: |
        sudo /etc/init.d/mysql start
        mysql -e 'CREATE DATABASE ${{ env.MYSQL_DATABASEE }};' -u${{ env.MYSQL_USERNAME }} -p${{ env.MYSQL_PASSWORD }}
    - name: Setup Database Config
      run: |
          cp config/settings/test.yml.sample config/settings/test.yml
          sed -i 's/MYSQL_HOST/${{ env.MYSQL_HOST }}/g' config/settings/test.yml
          sed -i 's/MYSQL_USERNAME/${{ env.MYSQL_USERNAME }}/g' config/settings/test.yml
          sed -i 's/MYSQL_PASSWORD/${{ env.MYSQL_PASSWORD }}/g' config/settings/test.yml
          sed -i 's/MYSQL_DATABASE/${{ env.MYSQL_DATABASE }}/g' config/settings/test.yml
    - name: Run tests
      run: bundle exec rake
