name: Bionomia

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: bitnami/mysql:8.3.0
        env:
          ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: bionomia_test
          MYSQL_USER: test
          MYSQL_PASSWORD: password
          MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    strategy:
      matrix:
        mysql: ['bitnami/mysql:8.3.0']
        elasticsearch: ['7.x-SNAPSHOT']
        ruby-version: ['3.2']
    env:
      RUBY_VERSION: 3.2.1
      BUNDLER_VERSION: 2.4.6
      RACK_ENV: test
      RUBY_YJIT_ENABLE: true
      MYSQL_USERNAME: test
      MYSQL_PASSWORD: password
      MYSQL_HOST: 0.0.0.0
      MYSQL_DATABASE: bionomia_test
    steps:
    - uses: actions/checkout@v3

    - name: Configure sysctl limits
      run: |
        sudo swapoff -a
        sudo sysctl -w vm.swappiness=1
        sudo sysctl -w fs.file-max=262144
        sudo sysctl -w vm.max_map_count=262144

    - name: Set up ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ env.RUBY_VERSION }}
        bundler-cache: true

    - name: Setup Database Config
      run: |
          cp config/settings/test.yml.sample config/settings/test.yml
          sed -i 's/MYSQL_HOST/${{ env.MYSQL_HOST }}/g' config/settings/test.yml
          sed -i 's/MYSQL_USERNAME/${{ env.MYSQL_USERNAME }}/g' config/settings/test.yml
          sed -i 's/MYSQL_PASSWORD/${{ env.MYSQL_PASSWORD }}/g' config/settings/test.yml
          sed -i 's/MYSQL_DATABASE/${{ env.MYSQL_DATABASE }}/g' config/settings/test.yml

    - name: Create database and import data
      run: |
          RACK_ENV=test bundle exec rake db:create:all
          RACK_ENV=test bundle exec rake db:schema:load
          RACK_ENV=test bundle exec rake db:seed:all

    - name: Runs Elasticsearch
      uses: elastic/elastic-github-actions/elasticsearch@master
      with:
        security-enabled: false
        stack-version: ${{ matrix.elasticsearch }}

    - name: Elasticsearch is reachable
      run: |
        curl --verbose --show-error http://localhost:9200

    - name: Run tests
      run: RACK_ENV=test bundle exec rake
