name: Bionomia

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_USER: test
          MYSQL_PASSWORD: password
          MYSQL_DATABASE: bionomia_test
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5 -e MYSQL_ROOT_PASSWORD=password -e MYSQL_USER=test -e MYSQL_PASSWORD=password -e MYSQL_DATABASE=bionomia_test --entrypoint sh mysql:8 -c "exec docker-entrypoint.sh mysqld --default-authentication-plugin=mysql_native_password"
    strategy:
      matrix:
        ruby-version: ['3.2']
    env:
      RUBY_VERSION: 3.2.1
      BUNDLER_VERSION: 2.4.6
      RACK_ENV: test
      RUBY_YJIT_ENABLE: true
      MYSQL_USERNAME: test
      MYSQL_PASSWORD: password
      MYSQL_HOST: localhost
      MYSQL_DATABASE: bionomia_test
    steps:
    - uses: actions/checkout@v3
    - name: Set up ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ env.RUBY_VERSION }}
        bundler-cache: true
#    - name: Set up MySQL
#      run: |
#        sudo /etc/init.d/mysql start
    - name: Setup Database Config
      run: |
          cp config/settings/test.yml.sample config/settings/test.yml
          sed -i 's/MYSQL_HOST/${{ env.MYSQL_HOST }}/g' config/settings/test.yml
          sed -i 's/MYSQL_USERNAME/${{ env.MYSQL_USERNAME }}/g' config/settings/test.yml
          sed -i 's/MYSQL_PASSWORD/${{ env.MYSQL_PASSWORD }}/g' config/settings/test.yml
          sed -i 's/MYSQL_DATABASE/${{ env.MYSQL_DATABASE }}/g' config/settings/test.yml
    - name: Create database and import data
      run: |
          RACK_ENV=test bundle exec rake db:create:all
          RACK_ENV=test bundle exec rake db:schema:load
    - name: Run tests
      run: RACK_ENV=test bundle exec rake
